[Settings]
  ID = "d88903eb-0bdd-4632-a1c0-cf828c2df91c"

[Build]
  Publish = ""
  Functions = ""

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  NODE_ENV = "development"
