[Settings]
  ID = "d88903eb-0bdd-4632-a1c0-cf828c2df91c"

[Build]
  Publish = "."
  Functions = ""
  command = "echo 'default context'"
# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.staging]
  command = "echo branch"
  base = "staging"
[context.staging.environment]
  NODE_ENV = "development"
